[field]
size = [400, 400]

[[waypoints]]
line = [[10, 10], [10, 390]]

[[waypoints]]
line = [[390, 10], [390, 390]]

[[obstacles]]
line = [[100, 0], [200, 180]]
width = 10

[[obstacles]]
line = [[100, 400], [200, 220]]
width = 10

[[obstacles]]
line = [[300, 0], [200, 180]]
width = 10

[[obstacles]]
line = [[300, 400], [200, 220]]
width = 10

[[pedestrians]]
origin = 0
destination = 1
spawn = { kind = "periodic", frequency = 100.0 }

[[pedestrians]]
origin = 1
destination = 0
spawn = { kind = "periodic", frequency = 100.0 }
