[field]
size = [200, 200]

[[waypoints]]
line = [[10, 10], [10, 190]]

[[waypoints]]
line = [[190, 10], [190, 190]]

[[obstacles]]
line = [[50, 0], [100, 90]]
width = 5

[[obstacles]]
line = [[50, 200], [100, 110]]
width = 5

[[obstacles]]
line = [[150, 0], [100, 90]]
width = 5

[[obstacles]]
line = [[150, 200], [100, 110]]
width = 5

[[pedestrians]]
origin = 0
destination = 1
spawn = { kind = "periodic", frequency = 100.0 }

[[pedestrians]]
origin = 1
destination = 0
spawn = { kind = "periodic", frequency = 100.0 }
