[field]
size = [100, 100]

[[waypoints]]
line = [[10, 10], [10, 90]]

[[waypoints]]
line = [[90, 10], [90, 90]]

[[obstacles]]
line = [[10, 0], [50, 45]]
width = 5

[[obstacles]]
line = [[10, 100], [50, 55]]
width = 5

[[obstacles]]
line = [[90, 0], [50, 45]]
width = 5

[[obstacles]]
line = [[90, 100], [50, 55]]
width = 5

[[pedestrians]]
origin = 0
destination = 1
spawn = { kind = "periodic", frequency = 100.0 }

[[pedestrians]]
origin = 1
destination = 0
spawn = { kind = "periodic", frequency = 100.0 }
