[[walls]]
polygon = [[1, 2], [10, 2], [10, 10], [-10, 10], [-10, 2], [-1, 2]]

[waypoints.0]
polygon = [[-10, 0], [-10, 2]]

[waypoints.1]
polygon = [[10, 0], [10, 2]]

[waypoints.2]
label = "door"
polygon = [[-1, 2], [1, 2]]

[waypoints.3]
label = "room"
polygon = [[-4, 6], [4, 6]]

[[pedestrians]]
origin = 0
waypoints = [2]
destination = 3
spawn = { kind = "periodic", interval = 1 }
despawn_on_arrival = true

[[pedestrians]]
origin = 1
waypoints = [2]
destination = 3
spawn = { kind = "periodic", interval = 1 }
despawn_on_arrival = true
