[field]
size = [1000, 1000]

[[waypoints]]
line = [[100, 0], [100, 100]]

[[waypoints]]
line = [[900, 900], [900, 1000]]

[[obstacles]]
line = [[0, 300], [800, 300]]

[[obstacles]]
line = [[200, 700], [1000, 700]]

[[pedestrians]]
origin = 0
destination = 1
spawn = { kind = "periodic", frequency = 200.0 }

[[pedestrians]]
origin = 1
destination = 0
spawn = { kind = "periodic", frequency = 100.0 }
