[field]
size = [100, 100]

[[waypoints]]
line = [[10, 0], [10, 10]]

[[waypoints]]
line = [[90, 90], [90, 100]]

[[obstacles]]
line = [[0, 30], [80, 30]]

[[obstacles]]
line = [[20, 70], [100, 70]]

[[pedestrians]]
origin = 0
destination = 1
spawn = { kind = "periodic", frequency = 2.0 }

[[pedestrians]]
origin = 1
destination = 0
spawn = { kind = "periodic", frequency = 1.0 }
