[field]
size = [10, 10]

[[waypoints]]
line = [[0, 0], [0, 1]]

[[waypoints]]
line = [[10, 9], [10, 10]]

[[obstacles]]
line = [[3, 0], [3, 8]]

[[obstacles]]
line = [[7, 2], [7, 10]]

[[pedestrians]]
origin = 0
destination = 1
spawn = { kind = "periodic", frequency = 2.0 }

[[pedestrians]]
origin = 1
destination = 0
spawn = { kind = "periodic", frequency = 1.0 }
