[field]
size = [20, 20]

[[waypoints]]
line = [[3, 3], [3, 17]]

[[waypoints]]
line = [[12, 3], [12, 17]]

[[obstacles]]
line = [[10, 0], [10, 10]]
width = 2

[[obstacles]]
line = [[10, 11], [10, 20]]
width = 2

[[pedestrians]]
origin = 0
destination = 1
spawn = { kind = "once", count = 40 }
