[field]
size = [20, 20]

[[waypoints]]
line = [[5, 3], [5, 17]]

[[waypoints]]
line = [[15, 3], [15, 17]]

[[obstacles]]
line = [[10, 0], [10, 10]]
width = 0.1

[[obstacles]]
line = [[10, 12], [10, 20]]
width = 0.1

[[pedestrians]]
origin = 0
destination = 1
# spawn = { kind = "periodic", frequency = 1.04 }
spawn = { kind = "once", count = 100 }

# [[pedestrians]]
# origin = 1
# destination = 0
# spawn = { kind = "periodic", frequency = 1.04 }
