[field]
size = [400, 400]

[[waypoints]]
line = [[10, 10], [10, 390]]

[[waypoints]]
line = [[390, 10], [390, 390]]

[[obstacles]]
line = [[0, 0], [0, 400]]
width = 0.2

[[obstacles]]
line = [[400, 0], [400, 400]]
width = 0.2

[[obstacles]]
line = [[0, 0], [400, 0]]
width = 0.2

[[obstacles]]
line = [[0, 400], [400, 400]]
width = 0.2

[[pedestrians]]
origin = 0
destination = 1
spawn = { kind = "periodic", frequency = 400.0 }

# [[pedestrians]]
# origin = 1
# destination = 0
# spawn = { kind = "periodic", frequency = 1.0 }
