[field]
size = [20, 10]

[[waypoints]]
line = [[5, 4], [5, 6]]

[[waypoints]]
line = [[15, 4], [15, 6]]

[[obstacles]]
line = [[5, 4], [15, 4]]

[[obstacles]]
line = [[5, 6], [15, 6]]

[[pedestrians]]
origin = 0
destination = 1
spawn = { kind = "periodic", frequency = 2.0 }
