[package]
name = "pedoni"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
bytemuck = { version = "1.16.1", features = ["derive"] }
clap = { version = "4.5.7", features = ["derive"] }
eframe = { version = "0.27.2", features = ["wgpu"] }
egui-wgpu = "0.27.2"
fastrand = "2.1.0"
fastrand-contrib = "0.1.0"
image = { version = "0.25.1", default-features = false, features = ["png", "jpeg"] }
nalgebra = { version = "0.33.0", features = ["serde", "serde-serialize"] }
once_cell = "1.19.0"
rayon = "1.10.0"
rustc-hash = "2.0.0"
serde = { version = "1.0.203", features = ["derive"] }
toml = "0.8.14"
