[package]
name = "pedoni"
version = "0.1.0"
edition = "2021"

[dependencies]
pedoni-simulator = { workspace = true }

anyhow = "1.0.86"
chrono = "0.4.38"
clap = { version = "4.5.7", features = ["derive"] }
env_logger = "0.11.5"
log = "0.4.22"
serde_json = "1.0.128"
toml = "0.8.14"
glam = "0.29.2"
plotters = { version = "0.3.7", default-features = false, features = [
    "bitmap_backend",
    "bitmap_gif",
    "full_palette",
] }

[dev-dependencies]
assert_float_eq = "1.1.3"
